- name: create management user 'orca'
  user:
    name: orca
    shell: /bin/bash
    comment: Orca Management User
    group: sudo

- name: Install ssh key for 'orca'
  authorized_key:
    user: orca
    key: "{{ lookup('file', orca_public_key ) }}"

- name: allow 'orca' to sudo without password
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: 'orca ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: disallow password authentication
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

- name: disallow root ssh
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh