- name: Install required packages
  become: yes
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - php7.2
    - php7.2-fpm 
    - php7.2-cli
    - php7.2-common
    - php7.2-curl
    - php7.2-xml 
    - php7.2-gd 
    - php7.2-mbstring
    - php7.2-zip 
    - php7.2-mysql
